Models/ErrorViewModel.cs
namespace CodeHelpRepoWebApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Reference.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace CodeHelpRepoWebApp.Models
{
	public class Reference
	{

        [Key]
		public int Id { get; set; }

        [Required]
		public string Language { get; set; }
        [Required]
        [UrlAttribute()]
		public string Link { get; set; }
        [Required]
		public string Keyphrase { get; set; }
        [Required]
        [DisplayName("Project Name")]
        public string ProjectName { get; set; }

        public DateTime CreatedDateTime { get; set; } = DateTime.Now.ToUniversalTime();

        public Reference()
        {
            Language = String.Empty;
            Link = String.Empty;
            Keyphrase = String.Empty;
            ProjectName = String.Empty;


        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CodeHelpRepoWebApp.Models;

namespace CodeHelpRepoWebApp.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ReferenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CodeHelpRepoWebApp.Data;
using CodeHelpRepoWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CodeHelpRepoWebApp.Controllers
{
    public class ReferenceController : Controller
    {

        private readonly ApplicationDBContext _db;
        private readonly IConfiguration _config;

        

        //Constructor
        public ReferenceController(ApplicationDBContext db, IConfiguration config)
        {
            _db = db;
            _config = config;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            

            IEnumerable<Reference> objReferenceList = _db.References;
            return View(objReferenceList);
        }

        //GET
        public IActionResult Create()
        {

            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Reference obj, string passcode)
        {
            string password = passcode;
            var CRUDcode = _config["Secrets:CRUDcode"];

            if (obj.Language == "default")
            {
                ModelState.AddModelError("CustomError", "Please select a coding language");
            }

            if (password == CRUDcode)
            {

                if (ModelState.IsValid)
                {
                    _db.References.Add(obj);
                    _db.SaveChanges();
                    TempData["success"] = "Reference saved";
                    return RedirectToAction("Index");
                }
            }
            else
            {
                ModelState.AddModelError("CustomError", "Wrong token, please try again or contact admin token help");
            }
            return View(obj);
        }

        //GET
        public IActionResult Edit(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }

            var referenceFromDB = _db.References.Find(id);

            if (referenceFromDB == null)
            {
                return NotFound();
            }

            return View(referenceFromDB);
        }

        //PUT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Reference obj, string passcode)
        {

             string password = passcode;
            var CRUDcode = _config["Secrets:CRUDcode"];

            if (obj.Language == "default")
            {
                ModelState.AddModelError("CustomError", "Please select a coding language");
            }

            if (password == CRUDcode)
            {
                if (ModelState.IsValid)
                {
                    _db.References.Update(obj);
                    _db.SaveChanges();
                    TempData["success"] = "Reference saved";
                    return RedirectToAction("Index");
                }
            }
            else
            {
                ModelState.AddModelError("CustomError", "Wrong token, please try again or contact admin token help");
            }
        
            
            return View(obj);
        }


        public IActionResult Delete(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }

            var referenceFromDB = _db.References.Find(id);

            if (referenceFromDB == null)
            {
                return NotFound();
            }

            return View(referenceFromDB);
        }

        //DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteReference(int? id, string passcode)
        {
            var referenceFromDB = _db.References.Find(id);
            string password = passcode;
            var DELETEcode = _config["Secrets:DELETEcode"];

            if (referenceFromDB == null)
            {
                return NotFound();
            }

            if (password == DELETEcode)
            {
                _db.References.Remove(referenceFromDB);
                _db.SaveChanges();
                TempData["success"] = "Reference Deleted";
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("CustomError", "Wrong token, please try again or contact admin token help");
                TempData["error"] = "Wrong token, please try again or contact admin token help";
            }

            
            return RedirectToAction("Delete", referenceFromDB);




        }





    }
}

Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CodeHelpRepoWebApp.Data;
using CodeHelpRepoWebApp.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CodeHelpRepoWebApp.Controllers
{
    public class SearchController : Controller
    {

        private readonly ApplicationDBContext _db;

        public SearchController(ApplicationDBContext db)
        {
            _db = db;
        }

        public IActionResult EmptyKeyword()
        {
            return View();
        }
        // GET: /<controller>/
        public IActionResult Index(string keyword)
        {
            if(!String.IsNullOrEmpty(keyword))
            {
                IEnumerable<Reference> objSearchList = _db.References.Where(r => r.Keyphrase.ToLower().Contains(keyword.ToLower())
                    || r.ProjectName.ToLower().Contains(keyword.ToLower()) || r.Language.ToLower().Contains(keyword.ToLower()));
                return View(objSearchList);
            }

            return RedirectToAction("EmptyKeyword");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "CR2 -Home Page";
}

<div class="text-center">
    <h1 class="display-4 mb-3 mt-4">Welcome!</h1>

</div>
<div classs="flex">
    <div class="row mt-3">

        <div class="col-6">
            <h3 class="mb-2 text-danger">Quickstart:</h3>
            <p class="mb-2 justify-fill">
                You have landed at the ultimate web app for organizing and saving your code reference links!

                As a software developer or casual coder, you know how important it is to have fast access code resources, especially the ones you have used before and likely will use again. CR2 is a web app I created as the final project for my software development course, and I'm excited to share it with you. With a sleek and intuitive interface, CR2 makes it easy to add and update code helps links.
                Currently there are no sign-in options, all users have access to the base repository.
            </p>
            <p class="mb-2">
                This means that you don't need to worry about creating an account or logging in.

                CR2 also allows you to search for links based on keyphrases and project names, so you can quickly find the resources you need.
            <p class="mb-2">
                How can add my own links?
                I would love to have fellow developers add to this repo, to contribute -simply request a developer token.
                </p>
                <p>
                I hope you enjoy using CR2 as much as I enjoyed creating it.

            </p>


        </div>

        <div class="col-6">
            <h3 class="text-danger ms-2">Notes:</h3>
            <ul class="text-danger">
                <li class="text-success">Pending: Pagination</li>
                <li class="text-success">Contributor tokens will be refreshed regularly</li>
                <li class="text-success">Repo <a href="https://github.com/dredelander/CodeReferenceDB" target=“_blank” >link</a>.</li>
                <li class="text-success">Special thanks to <a href="https://codelouisville.org/" target="_blank">Code Louisville</a> & the Spring 23'software development mentors (tue session). </li>
            </ul>
        </div>
    </div>
</div>
<div class="text-center mt-4">
    <p class="text-info mb-3" style="font-weight:bolder">
        To request a developer token, please email the admin.
        </p>
    <p class="mt-2 text-success">
        <a href="mailto:andres@landercentral.com"
        <i class="bi bi-envelope-at-fill ms-2"></i> andres@landercentral.com
        </a>
    </p>

</div>
<div class="text-center ">
   
    <p>Lets get <a asp-area="" asp-controller="Reference" asp-action="Index" class="text-danger"> started!</a>.</p>
</div>

Views/Reference/Create.cshtml
@model Reference


<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary"> Create a Reference</h2>
            <hr />

        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Language"></label>
            @*<input asp-for="Language" class="form-control" />*@
            <select asp-for="Language" class="form-select">
                <option value="default">Select from the dropdown:</option>
                <option value="C#">C#</option>
                <option value="Python">Python</option>
                <option value="JavaScript">JavaScript</option>
                <option value="PHP">PHP</option>
                <option value="Java">Java</option>
                <option value="Rust">Rust</option>
                <option value="SQL">SQL</option>
                <option value="Pandas">Python- Pandas</option>
            </select>
            <span asp-validation-for="Language" class="text-danger"></span>

        </div>
        <div class="mb-3">
            <label asp-for="Link"></label>
            <input asp-for="Link" class="form-control" />
            <span asp-validation-for="Link" class="text-danger"></span>

        </div>
        <div class="mb-3">
            <label asp-for="Keyphrase"></label>
            <input asp-for="Keyphrase" class="form-control" />
            <span asp-validation-for="Keyphrase" class="text-danger"></span>

        </div>
        <div class="mb-3">
            <label asp-for="ProjectName"></label>
            <input asp-for="ProjectName" class="form-control" />
            <span asp-validation-for="ProjectName" class="text-danger"></span>

        </div>
        <div class="mb-3">
            <label>Edit Code</label>
            <input type="text" name="passcode" required class="form-control" />


        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">
            Create
        </button>
        <a class="btn btn-secondary" asp-controller="Reference" asp-action="Index" style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts{
    @{

        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Reference/Delete.cshtml
@model Reference


<form method="post" asp-action="DeleteReference">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary"> Edit a Reference</h2>
            <hr />

        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Language"></label>
            <select asp-for="Language" class="form-select" disabled>
                <option value="default">Select from the dropdown:</option>
                <option value="C#">C#</option>
                <option value="Python">Python</option>
                <option value="JavaScript">JavaScript</option>
                <option value="PHP">PHP</option>
                <option value="Java">Java</option>
                <option value="Rust">Rust</option>
                <option value="SQL">SQL</option>
                <option value="Pandas">Python- Pandas</option>
            </select>
            <span asp-validation-for="Language" class="text-danger"></span>

        </div>
        <div class="mb-3">
            <label asp-for="Link"></label>
            <input asp-for="Link" class="form-control" disabled/>
            <span asp-validation-for="Link" class="text-danger"></span>

        </div>
        <div class="mb-3">
            <label asp-for="Keyphrase"></label>
            <input asp-for="Keyphrase" class="form-control" disabled />
            <span asp-validation-for="Keyphrase" class="text-danger"></span>

        </div>
        <div class="mb-3">
            <label asp-for="ProjectName"></label>
            <input asp-for="ProjectName" class="form-control" disabled/>
            <span asp-validation-for="ProjectName" class="text-danger"></span>

        </div>
        <div class="mb-3">
            <label>Delete Code</label>
            <input type="text" name="passcode" required class="form-control" />


        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">
            Delete
        </button>
        <a class="btn btn-secondary" asp-controller="Reference" asp-action="Index" style="width:150px">
            Back to List
        </a>
    </div>
</form>



@section Scripts{
    @{

        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Reference/Edit.cshtml
@model Reference


<form method="post" asp-action="Edit">
        <div class="border p-3 mt-4">
            <div class="row pb-2">
                <h2 class="text-primary"> Edit a Reference</h2>
                <hr />

            </div>
            <div asp-validation-summary="All"></div>
            <div class="mb-3">
                <label asp-for="Language"></label>
                @*<input asp-for="Language" class="form-control" />*@
                <select asp-for="Language" class="form-select">
                    <option value="default">Select from the dropdown:</option>
                    <option value="C#">C#</option>
                    <option value="Python">Python</option>
                    <option value="JavaScript">JavaScript</option>
                    <option value="PHP">PHP</option>
                    <option value="Java">Java</option>
                    <option value="Rust">Rust</option>
                    <option value="SQL">SQL</option>
                    <option value="Pandas">Python- Pandas</option>
                </select>
                <span asp-validation-for="Language" class="text-danger"></span>

            </div>
            <div class="mb-3">
                <label asp-for="Link"></label>
                <input asp-for="Link" class="form-control" />
                <span asp-validation-for="Link" class="text-danger"></span>

            </div>
            <div class="mb-3">
                <label asp-for="Keyphrase"></label>
                <input asp-for="Keyphrase" class="form-control" />
                <span asp-validation-for="Keyphrase" class="text-danger"></span>

            </div>
            <div class="mb-3">
                <label asp-for="ProjectName"></label>
                <input asp-for="ProjectName" class="form-control" />
                <span asp-validation-for="ProjectName" class="text-danger"></span>

            </div>
            <div class="mb-3">
                <label >Edit Code</label>
                <input type="text" name="passcode" required class="form-control" />
    

            </div>
            <button type="submit" class="btn btn-primary" style="width:150px">
                Update
            </button>
            <a class="btn btn-secondary" asp-controller="Reference" asp-action="Index" style="width:150px">
                Back to List
            </a>
        </div>
    </form>



@section Scripts{
    @{

        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Reference/Index.cshtml
@model IEnumerable<Reference>
@{

    ViewData["Title"] = "CR2 - List";
}



<div class="row pt-4">
    <div class="col-6 text-start">
        <a asp-controller="Reference" asp-action="Create" class="btn btn-danger">
            <i class="bi bi-plus-circle"></i> &nbsp Add a Reference Record
        </a>
    </div>
    <div class="col-6">
        <h2 class="text-primary"></h2>
    </div>

</div>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-12">
            <h2 class="text-info text-center" style="font-weight:bolder">Reference List</h2>
        </div>
        <div class="col-6 text-end">
        </div>
    </div>

    <br />
    <br />

    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th class="text-center">
                    Language
                </th>
                <th class="text-center">
                    Keyphrase
                </th>
                <th class="text-center">
                    Project Name
                </th>
                <th class="text-center">
                    Link
                </th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="10%">
                        @obj.Language
                    </td>
                    <td width="30%">
                        @obj.Keyphrase
                    </td>
                    <td width="30%">
                        @obj.ProjectName
                    </td>
                    <td width="10%" class="text-center">
                        <a href="@obj.Link" target=“_blank” >
                            <button class="btn btn-success">
                                Link

                            </button>
                        </a>

                    </td>
                    <td width="10%" class="text-center">
                        <div class=" w-75 btn-group" role="group">
                            <a asp-controller="Reference" asp-action="Edit" asp-route-id="@obj.Id">
                                <button class="btn btn-info">
                                   <i class="bi bi-pencil-square"></i> Edit
                                </button>
                            </a>
                        </div>
                    </td>
                    <td class="text-center">
                        <div class="w-75 btn-group danger" role="group">
                            <a asp-controller="Reference" asp-action="Delete" asp-route-id="@obj.Id">
                                <button class="btn btn-warning">
                                    <i class="bi bi-trash3"></i>
                                </button>
                            </a>
                        </div>
                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>

Views/Search/EmptyKeyword.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-12">
            <h2 class="text-info text-center" style="font-weight:bolder">Search Results</h2>
        </div>
        <div class="col-6 text-end">
        </div>
    </div>

    <br />
    <br />
    <h3>Sorry, please enter a keyword to activate the query</h3>
</div>

<div class="row pt-4">
    <a class="btn btn-secondary" asp-controller="Reference" asp-action="Index" style="width:150px">
        Back to List
    </a>
</div>

Views/Search/Index.cshtml
@model IEnumerable<Reference>


@{

    ViewData["Title"] = "CR2 - List";
}

@if (Model.Any())
{
    <div class="container p-3">
        <div class="row pt-4">
            <div class="col-12">
                <h2 class="text-info text-center" style="font-weight:bolder">Search Results</h2>
            </div>
            <div class="col-6 text-end">
            </div>
        </div>

        <br />
        <br />

        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th class="text-center">
                        Language
                    </th>
                    <th class="text-center">
                        Keyphrase
                    </th>
                    <th class="text-center">
                        Project Name
                    </th>
                    <th class="text-center">
                        Link
                    </th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td width="10%">
                            @obj.Language
                        </td>
                        <td width="30%">
                            @obj.Keyphrase
                        </td>
                        <td width="30%">
                            @obj.ProjectName
                        </td>
                        <td width="10%" class="text-center">
                            <a href="@obj.Link" target=“_blank”>
                                <button class="btn btn-success">
                                    Link

                                </button>
                            </a>

                        </td>
                        <td width="10%" class="text-center">
                            <div class=" w-75 btn-group" role="group">
                                <a asp-controller="Reference" asp-action="Edit" asp-route-id="@obj.Id">
                                    <button class="btn btn-info">
                                        <i class="bi bi-pencil-square"></i> Edit
                                    </button>
                                </a>
                            </div>
                        </td>
                        <td class="text-center">
                            <div class="w-75 btn-group danger" role="group">
                                <a asp-controller="Reference" asp-action="Delete" asp-route-id="@obj.Id">
                                    <button class="btn btn-warning">
                                        <i class="bi bi-trash3"></i>
                                    </button>
                                </a>
                            </div>
                        </td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div class="container p-3">
        <div class="row pt-4">
            <div class="col-12">
                <h2 class="text-info text-center" style="font-weight:bolder">Search Results</h2>
            </div>
            <div class="col-6 text-end">
            </div>
        </div>

        <br />
        <br />
        <h3>Sorry, nothing with this search params</h3>
    </div>

}
<div class="row pt-4">
<a class="btn btn-secondary" asp-controller="Reference" asp-action="Index" style="width:150px">
    Back to List
</a>
    </div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] -Code Reference Repo</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CodeHelpRepoWebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand"  style="color:white; font-weight:bolder" asp-area="" asp-controller="Home" asp-action="Index">Code Reference Repo: CR2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Reference" asp-action="Index">Reference List</a>
                        </li>

                    </ul>
                    <form class="d-flex" asp-action="Index" asp-controller="Search">
                        <input class="form-control me-sm-2" name="keyword" type="search" placeholder="Search">
                        <button class="btn btn-dark" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>


    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="text-center mt-2">

            <partial name="_Notifications" />
            </div>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary">
        <div class="container" style="color:white">
            &copy; 2023 -  <a href="https://www.landercentral.com">
    Lander Central  </a>

</div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notifications.cshtml
@if (TempData["success"] != null)
{
    <br />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.options = {
            "positionClass": "toast-top-center",
        }
        toastr.success('@TempData["success"]')
    </script>
}
@if (TempData["error"] != null)
{
    <br />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.options = {
            "positionClass": "toast-top-center",
        }
        toastr.error('@TempData["error"]')
    </script>
}